### Info
GET http://localhost:5126

### Games
GET http://localhost:5126/games

### Game by id
GET http://localhost:5126/games/2

### Game by id (bad)
GET http://localhost:5126/games/-1

### Add Game
POST http://localhost:5126/games
Content-Type: application/json

{
  "name": "Minecraft",
  "genreId": 5,
  "price": 19.99,
  "releaseDate": "2011-11-18"
}

### Add Game
POST http://localhost:5126/games
Content-Type: application/json

{
    "name": "Street Fighter II Turbo",
    "genreId": 1,
    "price": 9.99,
    "releaseDate": "1992-07-15"
}

### Add Game
POST http://localhost:5126/games
Content-Type: application/json

{
    "name": "Final Fantasy XIV",
    "genreId": 2,
    "price": 59.99,
    "releaseDate": "2010-09-30"
}

### Add Game (Bad)
POST http://localhost:5126/games
Content-Type: application/json

{
  "name": "Minecraft",
  "genreId": 5,
  "price": 19.99,
  "releaseDate": "2011-11-18"
}

### Add Game (Bad)
POST http://localhost:5126/games
Content-Type: application/json

{
  "name": "MinecraftMinecraftMinecraftMinecraftMinecraftMinecraftMinecraftMinecraftMinecraftMinecraftMinecraftMinecraftMinecraftMinecraftMinecraftMinecraftMinecraftMinecraftMinecraftMinecraftMinecraftMinecraftMinecraftMinecraftMinecraftMinecraftMinecraftMinecraftMinecraftMinecraftMinecraftMinecraftMinecraft",
  "genre": "Kids and Family",
  "price": 19.99,
  "releaseDate": "2011-11-18"
}

### Add Game (Bad)
POST http://localhost:5126/games
Content-Type: application/json

{
  "genre": "Kids and Family",
  "price": 19.99,
  "releaseDate": "2011-11-18"
}

### Update Game
PUT http://localhost:5126/games/1
Content-Type: application/json

{
  "name": "Minecraft",
  "genreId": 5,
  "price": 19.99,
  "releaseDate": "2011-11-18"
}

### Update Game
PUT http://localhost:5126/games/1
Content-Type: application/json

{
    "name": "Street Fighter II Turbo"
}

### Delete Game
DELETE http://localhost:5126/games/2